-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg/j1ySzL/dCoCSjIU
zsczKun1bdbXfNlyDXQNHVquIrOgCgYIKoZIzj0DAQehRANCAAQ1sTYXQzBxlS1i
E/YtWyG2QEFJhZjg3CHMrSS1zGQHA2RBjoc8HQCjzBlbLdZA0IHbDL4xnUu72JoJ
afIen31d
-----END PRIVATE KEY-----